---

- name: "{{ name }}.check"
  shell: |
    RING_CHECK=$(
        perl  -n -e '
        my $cont;
        while (<>) {
            # filter out lines beginnig with hash sign (optionally after whitespace)
            if (! /^\W*#/ ) {
                $cont .= $_;
            }
        }
        my $node=0;
        # search for all (sub)directives node { ... }
        while ($cont =~ m/\bnode\W*{[^}]*}/gs) {
            $node++;
            my $nodeStr=$&;
            # filter for key value pairs for ring adresses for ring0 and ring1
            if ($nodeStr =~ /(ring0_addr:\W*(.*))\W*(ring1_addr:\W*(.*))\W*/g) {
                if ( $2 ne "" and $4 ne "" ) {
                    # report a "2", if both attributes are set with values
                    print "2"
                }
            }
        }
        printf "\n"' < /etc/corosync/corosync.conf
    )
    [[ "$RING_CHECK" == "22" ]] && exit 0
    exit 1
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
